name: Build for Desktop

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Update apt repositories
        run: sudo apt update
      - name: Download prerequisite apt packages
        run: sudo apt install
          libwebkit2gtk-4.1-dev
          build-essential
          curl
          wget
          file
          libxdo-dev
          libssl-dev
          libayatana-appindicator3-dev
          librsvg2-dev
          gcc-aarch64-linux-gnu
      - run: rustup target add x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu
      - run: ENV PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu=/usr/lib/aarch64-linux-gnu/pkgconfig
      - run: npm install
      - run: npm run build-tauri-arm64-linux
      - run: npm run build-tauri-x64-linux
      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: game3d
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/rpm/*.rpm
            src-tauri/target/release/bundle/appimage/*.AppImage
  build-macos:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: rustup target add aarch64-apple-darwin
      - run: npm install
      - run: npm run build-tauri-arm64-macos
      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: game3d
          path: |
            src-tauri/target/release/bundle/macos/game3d.app/**
            src-tauri/target/release/bundle/dmg/*.dmg
  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: rustup target add x86_64-pc-windows-msvc aarch64-pc-windows-msvc
      - run: npm install
      - run: npm run build-tauri-arm64-windows
      - run: npm run build-tauri-x64-windows
      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: game3d
          path: |
            src-tauri\target\release\bundle\msi\*.msi
            src-tauri\target\release\bundle\nsis\*.exe